name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd6b5329a336b14e2935ab1729fa0e08f2a1bac6e044eb7bb203b27a5762a30f"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
