name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4aaf515e9c1e000f8c7d2b5c493f7244270d3ee185f2b1869db71b90855aa0c9"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
