name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "510c20afcee9a8dd30a7f9a7f87ca68153d6a8295f1160be8a61faadde017c68"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
