name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c63d05419c2a7c4d64be2f4b2cdb4df872f55eb87e25613bab45c1f050055a8c"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
