name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "902a2d2a8660626e2145da7c9778b1ae1a60855563310e60f8508d04ba6fa17a"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
