name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c0240d1630e1c361f10a70c1ae3b955c3f854a9f14142390529e30605c3edb1"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
