name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff61d7a7850aa697a6038b945f93f8357a45fdb8703b0e1abb1019f2fb3c5219"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
