name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca2bb1d5e6601fba2a74e447dd91d8613229fa0bd48d62b823fa9abb718f2186"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
