name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27bf0257c17ed457f75afebf5bd0ccaa6b8a54f0fcdad6474b7610c8619b62a8"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
