name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a1745e9a8a94b304b7f59e94858b83723f9c4d113c18f0892e1707d7864fe32"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
