name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52fa45aeccc5883ab63c3bcb1bd24963f08ed028de0094b9f73bebfe3c8bd661"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
