name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd983f06007cc29c9d0165c1001d0bad4de0e13bb8d47572bc667edc966e47b3"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
