name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cd1f75f72a815c2fe8be7b68ca2e35029ce6fc243c10943086d63cb1eab77ba"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
