name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc06c844e1ee3c416d6f72e6585fb5f28a97a2598a2dc14bbe61d534c88244d6"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
