name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d089dd3a0896ccd7875bf374bb048ba266c7a11a568a5c72cdc115593f8bf37"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
