name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9aed247770d885e305c61935016be33435572e272a9463e8c0974d359b791b2a"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
