name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0cfccb688dd1550b326ccbe77a4ef147bb26ec65dc1fbb5de8b28ebf1aeeb02"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
