name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b87cecee6287bd9203581488230bd66216bd3dc5ecccc0850904481597970aa5"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
