name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce4ee5911dc213ae2948b770069cac822c26f8dd22f3a5074f31d4fe1a82ceec"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
