name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7758d1da80e7763f2cc98ca24b35b3f3ccccb0daf95406b177a541d6d0bb9064"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
