name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfc4f91e4c85d1cb10dc0f3ce3269750b1cdd5873e2347d86aaa9cad43974a8b"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
