name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1cd01d6ba588629943ef6dc7132e284ebb35c93a93ce0ec345d16baf5a2c6ed"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
