name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ee65d96d88f465681618acc9e54b72d928208d876def57690675b97951af289"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
