name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bb238329afdfeebc694faad04fa7c44ad71b91637ae8d84ffba85a1245fbee3"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
