name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fa3d780ce743e82b9349fe4e497a1b7372e380bc1229fe3139cfc6d99150399"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
