name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a8f6202d0db190b4e85469710af2b4a5350a586de9f8a1f9d3a276aa40aa8e7"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
