name = "Modpack"
author = "Jorge Pereira"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a87c5e000578ddc0632879095ae4161c36d7fbb72e95ccfd3d121e4b4d9f9ce1"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
