#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Aug 05 21:44:47 BRT 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=ComplementaryReimagined_r5.2.2.zip
enableShaders=true
